Reports_VOB/Controllers/ActividadController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using VOB.Web.Utilidades;

namespace VOB.Web.Controllers
{
    public class ActividadController : Utilidades.BaseController
    {
        public ActionResult Index(Models.ReporteNormalModel model)
        {
            ModelState.Clear();

            model.IdTipoBalance = 4;
            model.TituloBalance = "Conceptual";
            ViewBag.Title = "Banco Internacional - Reporte Financiero Conceptual";
            ViewBag.UserName = UsuarioNT;

            if (!string.IsNullOrEmpty(model.Rut))
            {
                WSHelper.WebService service = new WSHelper.WebService(ConfigHelper.ObtenerString("ReportWebServiceURLTesting"), "ConsultaCliente");
                service.Params.Add("RutCliente", model.Rut);
                service.Invoke();

                string ns = "{" + ConfigHelper.ObtenerString("ReportWebServiceNamespace") + "}";
                foreach (XElement xe in service.ResultXML.Descendants(ns + "ConsultaClienteResponse").Descendants(ns + "ConsultaClienteResult"))
                {
                    string estado; 
                    estado = (string)xe.Element(ns + "Estado");

                    if (estado != null && estado.ToUpper() == "OK")
                    {
                        foreach (XElement info in xe.Descendants(ns + "InformacionCliente"))
                        {
                            string tipoPersona = (string)info.Element(ns + "TipoCliente");

                            if (tipoPersona.ToUpper() == "PERSONA")
                            {
                                foreach (XElement per in info.Descendants(ns + "Persona"))
                                {
                                    string nombre, apePaterno, apeMaterno;
                                    nombre = (string)per.Element(ns + "NombreCliente");
                                    apePaterno = (string)per.Element(ns + "ApellidoPaterno");
                                    apeMaterno = (string)per.Element(ns + "ApellidoMaterno");
                                    model.ClienteNombre = string.Concat(nombre, " ",apePaterno, " ", apeMaterno);

                                    foreach (XElement eje in per.Descendants(ns + "EjecutivoAsociado"))
                                    {
                                        model.EjecutivoId = !string.IsNullOrEmpty((string)eje.Element(ns + "IdEjecutivo")) ? (int)eje.Element(ns + "IdEjecutivo") : 0;
                                        model.EjecutivoRut = !string.IsNullOrEmpty((string)eje.Element(ns + "RutEjecutivo")) ? ((string)eje.Element(ns + "RutEjecutivo")).TrimStart('0') : "";
                                        model.EjecutivoNombre = (string)eje.Element(ns + "NombreEjecutivo");
                                    }
                                }
                            }
                            if (tipoPersona.ToUpper() == "EMPRESA")
                            {
                                foreach (XElement emp in info.Descendants(ns + "Empresa"))
                                {
                                    model.ClienteNombre = (string)emp.Element(ns + "NombreCliente");

                                    foreach (XElement eje in emp.Descendants(ns + "EjecutivoAsociado"))
                                    {
                                        model.EjecutivoId = !string.IsNullOrEmpty((string)eje.Element(ns + "IdEjecutivo")) ? (int)eje.Element(ns + "IdEjecutivo") : 0;
                                        model.EjecutivoRut = !string.IsNullOrEmpty((string)eje.Element(ns + "RutEjecutivo")) ? ((string)eje.Element(ns + "RutEjecutivo")).TrimStart('0') : "";
                                        model.EjecutivoNombre = (string)eje.Element(ns + "NombreEjecutivo");
                                    }
                                }
                            }
                        }

                        model.EjecutivoNombre = JsonConvert.SerializeObject(model);
                    }
                    else
                    {
                        model.ClienteNombre = "Cliente no EXISTE";
                    }
                }

                if (string.IsNullOrEmpty(model.ClienteNombre))
                {
                    model.ClienteNombre = service.ResultXML.ToString();
                }
            }

            return View(model);
        }
    }
}

Reports_VOB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/KendoCss")
</head>
<body>
    <div id="layout-header" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <img id="layout-header-image" class="img-responsive" src="@Url.Content("~/Images/logo-bancointernacional.png")" />
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Estados Financieros: ", "Individual", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Individual", "Individual", "Home", new { }, new { @id="lnkIndividual" })</li>
                    <li>@Html.ActionLink("Consolidado", "Consolidado", "Home", new { }, new { @id = "lnkConsolidado" })</li>
                    <li>@Html.ActionLink("Combinado", "Combinado", "Home", new { }, new { @id = "lnkCombinado" })</li>
                    <li>@Html.ActionLink("Conceptual", "Index", "Actividad", new { }, new { @id = "lnkConceptual" })</li>
                </ul>
                <p class="nav navbar-text navbar-right strongwhite">Bienvenido, @ViewBag.UserName!</p>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer class="footer container" style="z-index:1;">
            <p class="pull-left white">&copy; @DateTime.Now.Year - @ViewBag.Title</p>    
            <p class="pull-right white">Desarrollado por Iconexa S.A</p>
        </footer>
    </div>
    <footer class="footer" style="width:100%; z-index:0;">
        
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/KendoJs")
    @Scripts.Render("~/bundles/Utilities")
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        @Scripts.Render("~/bundles/IE8Crap")
    <![endif]-->
    @RenderSection("scripts", required: false)
</body>
</html>